In [30]:
print("hello")

hello

In [31]:
import pandas as pd
import numpy as np
import seaborn as sp

In [32]:
red=pd.read_csv("dataset\Reddit_Data.csv")
twi=pd.read_csv("dataset\Twitter_Data.csv")

<>:1: SyntaxWarning: invalid escape sequence '\R'
<>:2: SyntaxWarning: invalid escape sequence '\T'
<>:1: SyntaxWarning: invalid escape sequence '\R'
<>:2: SyntaxWarning: invalid escape sequence '\T'
C:\Users\siva\AppData\Local\Temp\ipykernel_6776\45941711.py:1: SyntaxWarning: invalid escape sequence '\R'
  red=pd.read_csv("dataset\Reddit_Data.csv")
C:\Users\siva\AppData\Local\Temp\ipykernel_6776\45941711.py:2: SyntaxWarning: invalid escape sequence '\T'
  twi=pd.read_csv("dataset\Twitter_Data.csv")

In [33]:
red.head()

                                       clean_comment  category
0   family mormon have never tried explain them t...         1
1  buddhism has very much lot compatible with chr...         1
2  seriously don say thing first all they won get...        -1
3  what you have learned yours and only yours wha...         0
4  for your own benefit you may want read living ...         1

In [34]:
twi.head()

                                          clean_text  category
0  when modi promised “minimum government maximum...      -1.0
1  talk all the nonsense and continue all the dra...       0.0
2  what did just say vote for modi  welcome bjp t...       1.0
3  asking his supporters prefix chowkidar their n...       1.0
4  answer who among these the most powerful world...       1.0

In [35]:
red.dropna(inplace=True)
twi.dropna(inplace=True)

red = red.drop_duplicates()
twi = twi.drop_duplicates()

In [36]:
red = red[["clean_comment", "category"]]
twi = twi[["clean_text", "category"]]

In [37]:
red = red.rename(columns={"clean_comment":"text"})
twi = twi.rename(columns={"clean_text":"text"})

In [38]:
df = pd.concat([red, twi], ignore_index=True)

In [39]:
import re

def clean_text(text):
    text = str(text).lower()
    text = re.sub(r"http\S+", "", text)
    text = re.sub(r"[^a-zA-Z ]", "", text)
    return text

df["text"] = df["text"].apply(clean_text)

In [40]:
from sklearn.model_selection import train_test_split

X = df["text"]
y = df["category"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [41]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression

In [42]:
tfidf = TfidfVectorizer(stop_words="english")

In [ ]:
X_train_tfidf = tfidf.fit_transform(X_train)
X_est_tfidf = tfidf.transform(X_test)

In [ ]:
from sklearn.metrics import accuracy_score

pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, pred))

In [ ]:
model.predict(["This movie is amazing"])
model.predict(["Worst product ever"])